import type { PlanAnalysis, RiskLevel, VulnerabilitySeverity } from '@/types/analysis';

const RISK_COLORS: Record<RiskLevel, [number, number, number]> = {
  HIGH:   [185,  28,  28],
  MEDIUM: [161,  98,   7],
  LOW:    [ 21, 128,  61],
};

export async function generatePdfReport(analysis: PlanAnalysis): Promise<void> {
  const { default: jsPDF } = await import('jspdf');
  const { default: autoTable } = await import('jspdf-autotable');

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 15;
  const contentW = pageW - margin * 2;
  let y = margin;

  // ── helpers ──────────────────────────────────────────────────────────────────

  function checkPageBreak(neededHeight: number) {
    if (y + neededHeight > pageH - 20) {
      doc.addPage();
      y = margin;
    }
  }

  function sectionTitle(title: string) {
    checkPageBreak(12);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(40, 40, 40);
    doc.text(title, margin, y);
    y += 6;
    doc.setDrawColor(200, 200, 200);
    doc.setLineWidth(0.3);
    doc.line(margin, y, margin + contentW, y);
    y += 5;
  }

  function addPageFooters() {
    const totalPages: number = doc.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(8);
      doc.setTextColor(150, 150, 150);
      doc.text('Terraform Plan Explainer', margin, pageH - 8);
      doc.text(`Page ${i} of ${totalPages}`, pageW - margin, pageH - 8, { align: 'right' });
    }
  }

  // ── 1. Header ─────────────────────────────────────────────────────────────────

  doc.setFillColor(30, 30, 46);
  doc.rect(0, 0, pageW, 32, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.setTextColor(255, 255, 255);
  doc.text('Terraform Plan Analysis Report', pageW / 2, 13, { align: 'center' });

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(180, 180, 200);
  doc.text('Generated by Terraform Plan Explainer', pageW / 2, 20, { align: 'center' });

  const timestamp = new Date().toLocaleString('en-US', {
    dateStyle: 'long', timeStyle: 'short',
  });
  doc.text(`Report generated: ${timestamp}`, pageW / 2, 26, { align: 'center' });

  y = 42;

  // ── 2. Risk Level ─────────────────────────────────────────────────────────────

  sectionTitle('Risk Level');

  const riskColor = RISK_COLORS[analysis.riskLevel];
  doc.setFillColor(...riskColor);
  doc.roundedRect(margin, y, 40, 9, 2, 2, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.text(`${analysis.riskLevel} RISK`, margin + 20, y + 6, { align: 'center' });

  y += 14;

  const summaryLines = doc.splitTextToSize(analysis.summary, contentW);
  checkPageBreak(summaryLines.length * 5 + 4);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 5 + 8;

  // ── 3. Resource Counts ────────────────────────────────────────────────────────

  sectionTitle('Resource Counts');

  const { added, changed, destroyed } = analysis.counts;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(`Added: ${added}   /   Changed: ${changed}   /   Destroyed: ${destroyed}`, margin, y);
  y += 10;

  // ── 4. Warnings ───────────────────────────────────────────────────────────────

  if (analysis.warnings.length > 0) {
    sectionTitle('Warnings');

    const warnLines: string[] = [];
    for (const w of analysis.warnings) {
      const wrapped = doc.splitTextToSize(`• ${w}`, contentW - 8);
      warnLines.push(...wrapped);
    }

    checkPageBreak(warnLines.length * 5 + 8);
    doc.setFillColor(255, 240, 240);
    doc.setDrawColor(220, 100, 100);
    doc.setLineWidth(0.3);
    doc.rect(margin, y, contentW, warnLines.length * 5 + 6, 'FD');

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(180, 30, 30);
    doc.text(warnLines, margin + 4, y + 5);
    y += warnLines.length * 5 + 12;
  }

  // ── 5. Resource Changes ───────────────────────────────────────────────────────

  if (analysis.changes.length > 0) {
    sectionTitle('Resource Changes');

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Action', 'Resource', 'Description', 'Destructive']],
      body: analysis.changes.map((c) => [
        c.action.toUpperCase(),
        c.resource,
        c.description,
        c.isDestructive ? 'Yes' : 'No',
      ]),
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: [30, 30, 46], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 22, fontStyle: 'bold' },
        1: { cellWidth: 55, font: 'courier' },
        3: { cellWidth: 22, halign: 'center' },
      },
      didParseCell(data) {
        if (data.column.index === 0 && data.section === 'body') {
          const action = String(data.cell.raw ?? '').toLowerCase();
          const colorMap: Record<string, [number, number, number]> = {
            create:  [21, 128, 61],
            update:  [161, 98, 7],
            destroy: [185, 28, 28],
            replace: [194, 65, 12],
          };
          const c = colorMap[action];
          if (c) data.cell.styles.textColor = c;
        }
        if (data.column.index === 3 && data.section === 'body') {
          if (data.cell.raw === 'Yes') data.cell.styles.textColor = [185, 28, 28];
        }
      },
    });

    y = (doc as any).lastAutoTable.finalY + 10;
  }

  // ── 6. Cost Estimate ──────────────────────────────────────────────────────────

  const cost = analysis.costEstimate;
  sectionTitle('Cost Estimate');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(
    `Monthly: $${cost.monthlyTotal.toFixed(2)} USD   /   Yearly: $${cost.yearlyTotal.toFixed(2)} USD`,
    margin, y,
  );
  y += 6;
  doc.setFontSize(9);
  doc.setTextColor(100, 100, 100);
  doc.text(`Provider: ${cost.provider}   |   Confidence: ${cost.confidence}`, margin, y);
  y += 8;

  if (cost.breakdown.length > 0) {
    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Resource', 'Type', 'Est. Monthly', 'Assumptions']],
      body: cost.breakdown.map((r) => [
        r.resource,
        r.type,
        r.monthlyCost === 0 ? '$0.00 / free' : `$${r.monthlyCost.toFixed(2)}`,
        r.assumptions,
      ]),
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: [30, 30, 46], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 55, font: 'courier' },
        2: { cellWidth: 28, halign: 'right' },
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  }

  // ── 7. Vulnerability Context ──────────────────────────────────────────────────

  const vuln = analysis.vulnerabilityContext;
  sectionTitle('Vulnerability Context');

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(50, 50, 50);
  doc.text(
    `${vuln.findings.length} finding${vuln.findings.length !== 1 ? 's' : ''} across ${vuln.scannedResources} scanned resource${vuln.scannedResources !== 1 ? 's' : ''}`,
    margin, y,
  );
  y += 8;

  if (vuln.findings.length > 0) {
    const severityColors: Record<VulnerabilitySeverity, [number, number, number]> = {
      CRITICAL:      [185,  28,  28],
      HIGH:          [194,  65,  12],
      MEDIUM:        [161,  98,   7],
      LOW:           [ 29, 100, 180],
      INFORMATIONAL: [100, 100, 100],
    };

    autoTable(doc, {
      startY: y,
      margin: { left: margin, right: margin },
      head: [['Resource', 'Version', 'CVE ID', 'Severity', 'Recommendation']],
      body: vuln.findings.map((f) => [
        f.resource,
        f.currentVersion,
        f.cveId,
        f.severity,
        f.recommendation,
      ]),
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: [30, 30, 46], textColor: 255, fontStyle: 'bold' },
      columnStyles: {
        0: { cellWidth: 45, font: 'courier' },
        1: { cellWidth: 28 },
        2: { cellWidth: 28, font: 'courier' },
        3: { cellWidth: 22, halign: 'center', fontStyle: 'bold' },
      },
      didParseCell(data) {
        if (data.column.index === 3 && data.section === 'body') {
          const sev = String(data.cell.raw ?? '') as VulnerabilitySeverity;
          const c = severityColors[sev];
          if (c) data.cell.styles.textColor = c;
        }
      },
    });

    y = (doc as unknown as { lastAutoTable: { finalY: number } }).lastAutoTable.finalY + 10;
  } else {
    checkPageBreak(10);
    doc.setFont('helvetica', 'italic');
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.text('No known vulnerabilities detected.', margin, y);
    y += 10;
  }

  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  const vulnDisclaimer = doc.splitTextToSize(vuln.disclaimer, contentW);
  checkPageBreak(vulnDisclaimer.length * 5 + 8);
  doc.text(vulnDisclaimer, margin, y);
  y += vulnDisclaimer.length * 5 + 8;

  // ── 8. Disclaimer ─────────────────────────────────────────────────────────────

  checkPageBreak(20);
  sectionTitle('Disclaimer');

  const disclaimerText = doc.splitTextToSize(
    `${cost.disclaimer}\n\nThis report is generated automatically from a Terraform plan and should be reviewed by a qualified engineer before making infrastructure decisions.`,
    contentW,
  );
  doc.setFont('helvetica', 'italic');
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text(disclaimerText, margin, y);

  // ── Page footers ──────────────────────────────────────────────────────────────

  addPageFooters();

  // ── Save ──────────────────────────────────────────────────────────────────────

  const filename = `terraform-plan-report-${new Date().toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
